name: System Check

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows you to click a button to run it manually

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the bot to save state.json back to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install packages
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SELLERS: ${{ secrets.SELLERS }}
        run: python app.py

      - name: Save memory back to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add state.json
          git commit -m "update state" || echo "No changes to memory"
          git push
